name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.2
    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "NODE_ENV=production" >> .env
        echo "PORT=3000" >> .env
      env:
        DOTENV_PATH: .env

    - name: Run tests
      run: npm test
